#!/bin/bash

# Check that exactly 5 arguments are given
if [ "$#" -ne 5 ]; then
  echo "Usage: ./private_prove <msgHash> <r> <s> <pubX> <pubY>"
  exit 1
fi

msgHash="$1"
r="$2"
s="$3"
pubX="$4"
pubY="$5"

sed -i \
  -e "s/\"msgHash\": \"\"/\"msgHash\": \"$msgHash\"/" \
  -e "s/\"r\": \"\"/\"r\": \"$r\"/" \
  -e "s/\"s\": \"\"/\"s\": \"$s\"/" \
  -e "s/\"pubY\": \"\"/\"pubY\": \"$pubY\"/" \
  witness_input.json

go run prove_blinded_k1.go
